export const BasicMiss = {
  "阿贝多": ['a', 'z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "阿蕾奇诺": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "埃洛伊": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "艾尔海森": [ 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "艾梅莉埃": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "爱可菲": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "安柏": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "八重神子": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "芭芭拉": ['a', 'c', 'q', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "白术": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "班尼特": ['a', 'z', 'c', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "北斗": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "达达利亚": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "迪奥娜": ['a', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "迪卢克": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "迪希雅": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "多莉": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "珐露珊": ['a', 'c', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "菲米尼": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "菲谢尔": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "枫原万叶": ['a', 'z', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "芙宁娜": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "甘雨": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "胡桃": ['c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "荒泷一斗": ['c', 'q', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "基尼奇": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "嘉明": ['a', 'z', 'e', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "九条裟罗": ['a', 'c', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "久岐忍": ['a', 'z', 'c', 'f', 'y', 'dph', 'hph', 'dps', 'hps'],
  "卡齐娜": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "卡维": ['z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "凯亚": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "坎蒂丝": ['z', 'c', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "柯莱": ['a', 'z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "可莉": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "克洛琳德": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "刻晴": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "莱欧斯利": ['c', 'e', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "莱依拉": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "蓝砚": ['a', 'z', 'c', 'f', 'y', 'dph', 'hph', 'dps', 'hps'],
  "雷电将军": ['a', 'c', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "雷泽": ['z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "丽莎": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "林尼": ['a', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "琳妮特": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "流浪者": ['c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "鹿野院平藏": ['c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "罗莎莉亚": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "玛拉妮": ['z', 'c', 'e', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "玛薇卡": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "梦见月瑞希": ['a', 'z', 'c', 'f', 'y', 'dph', 'hph', 'dps', 'hps'],
  "米卡": ['z', 'c', 'q', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "莫娜": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "那维莱特": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "纳西妲": ['a', 'c', 'q', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "娜维娅": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "妮露": ['a', 'z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "凝光": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "诺艾尔": ['c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "欧洛伦": ['a', 'z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "七七": ['a', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "绮良良": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "恰斯卡": [ 'c', 'e', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "千织": ['f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "茜特菈莉": ['a', 'z', 'c', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "琴": ['a', 'c', 'f', 'y', 'dph', 'hph', 'dps', 'hps'],
  "赛诺": ['z', 'c', 'q', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "赛索斯": ['c', 'q', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "砂糖": ['c', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "珊瑚宫心海": ['a', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "申鹤": ['a', 'z', 'c', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "神里绫华": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "神里绫人": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "丝柯克": ['f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "塔利雅": ['f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "提纳里": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "托马": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "瓦雷莎": ['a', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "温迪": ['a', 'z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "五郎": ['c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "希格雯": ['a', 'c', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "希诺宁": ['z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "夏洛蒂": ['a', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "夏沃蕾": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "闲云": ['a', 'z', 'y', 'dph', 'hph', 'dps', 'hps'],
  "香菱": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "宵宫": ['c', 'e', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "魈": ['q', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "辛焱": ['a', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "行秋": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "烟绯": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "瑶瑶": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "夜兰": ['a', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "伊安珊": ['a', 'c', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "伊法": ['a', 'z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "优菈": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "云堇": ['a', 'z', 'c', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "早柚": ['a', 'z', 'c', 'f', 'y', 'dph', 'hph', 'dps', 'hps'],
  "钟离": ['z', 'c', 'f', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "重云": ['z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],

  "旅行者/null": ['e', 'q', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "旅行者/anemo": ['a', 'z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "旅行者/geo": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "旅行者/electro": ['a', 'z', 'c', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "旅行者/dendro": ['a', 'z', 'c', 'f', 'h', 'y', 'dph', 'hph', 'dps', 'hps'],
  "旅行者/hydro": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "旅行者/pyro": ['a', 'z', 'c', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps'],
  "旅行者/cryo": ['a', 'z', 'c', 'e', 'q', 'f', 'h', 'y', 'r', 'dph', 'hph', 'dps', 'hps']

}
