group: 预下载详情
list:
  - icon: 1
    title: 桌面端
    desc: 默认使用PC端4语音
  - icon: 2
    title: 移动端
    desc: 默认使用安卓端4语音
  - icon: 1
    title: '4.0.0'
    desc: 34.06GB
  - icon: 2
    title: '4.0.0'
    desc: 10.54GB
  - icon: 1
    title: '4.1.0'
    desc: 15.83GB
  - icon: 2
    title: '4.1.0'
    desc: 4.99GB
  - icon: 1
    title: '4.2.0'
    desc: 15.10GB
  - icon: 2
    title: '4.2.0'
    desc: 4.24GB
  - icon: 1
    title: '4.3.0'
    desc: 12.54GB
  - icon: 2
    title: '4.3.0'
    desc: 3.59GB
  - icon: 1
    title: '4.4.0'
    desc: 9.21GB
  - icon: 2
    title: '4.4.0'
    desc: 3.58GB
  - icon: 1
    title: '4.5.0'
    desc: 6.23GB
  - icon: 2
    title: '4.5.0'
    desc: 2.57GB
  - icon: 1
    title: '4.6.0'
    desc: 38.77GB
  - icon: 2
    title: '4.6.0'
    desc: 9.90GB
  - icon: 1
    title: '4.7.0'
    desc: 28.01GB
  - icon: 2
    title: '4.7.0'
    desc: 2.49GB
  - icon: 1
    title: '4.8.0'
    desc: 22.93GB
  - icon: 2
    title: '4.8.0'
    desc: 2.13GB